version: '3.5'

services:
  new-website:
    env_file: .env
    build: .
    volumes:
      - ./core:/var/www
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php-overrides.ini
    working_dir: /var/www
    container_name: ${APP_CONTAINER_NAME}
    networks:
      - ouredu-service-app


  postgresql-new-website:
    env_file: .env
    image: 'postgis/postgis:latest'
    container_name: ${MAIN_DB_CONTAINER_NAME}
    command: '-p ${MAIN_DB_PORT}' # running the container on port 1111
    ports:
      - ${MAIN_DB_PORT}:5432
    environment:
      POSTGRES_DB: ouredu-new-website
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: secret
    volumes:
      - "./.docker-data/dbdata:/var/lib/postgresql"
      - ".docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf"
      - ".docker/postgres/pg_hba.conf:/usr/share/postgresql/13/pg_hba.conf"
    networks:
      - ouredu-service-app
  new-website-nginx:
    env_file: .env
    build: ./.docker/nginx
    restart: always
    container_name: ${APP_NGINX_CONTAINER_NAME}
    ports:
      - "${APP_NGINX_PORT}:80"
    volumes:
      - ./core:/var/www
    depends_on:
      - new-website
    environment:
      - NGINX_HOST=oureducation.test
      - NGINX_PORT=80
    networks:
      ouredu-service-app:
        aliases:
          - app-nginx



networks:
  ouredu-service-app:
    name: ${OUR_EDU_NETWORK_NAME}
    external: true
    driver: bridge
